[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#7b8292"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011"
key = "F1"

[[keyboard.bindings]]
chars = "\u0011t"
key = "F2"

[[keyboard.bindings]]
chars = "\u0011v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00111"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00112"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00113"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00114"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00115"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00116"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00117"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00118"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00119"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011p"
key = "Left"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u0011n"
key = "Right"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u0011H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011\u0006"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011\u001B[D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0011\u001B[B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0011\u001B[A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0011\u001B[C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001A"
key = "Z"
mods = "Control"

[mouse]
hide_when_typing = false

# [mouse.hints]
# launcher = "open"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
opacity = 0.85
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
