#!/usr/bin/env bash

###----------------------------------------
##   Menu Bar with Sketchybar
#------------------------------------------
# This is inspired by many community resources. Here is some that I specifically
# referred to for my setup:
# https://github.com/Jac-Zac/My-home-config/blob/master/.config/sketchybar/sketchybarrc
# https://github.com/mCassy/sketchybarc


. "./colours.sh" # Loads all defined colors
. "./icons.sh"  # Loads all defined icons

ITEM_DIR="./items"
PLUGIN_DIR="./plugins"

FONT="Hack Nerd Font"
# SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=8

CORNER_RADIUS=4
SHADOW=off


sketchybar --bar height=35 \
	color="$TRANSPARENT" \
	shadow="$SHADOW" \
	position=top \
	sticky=on \
	padding_right=6 \
	padding_left=6 \
	corner_radius="$CORNER_RADIUS" \
	y_offset=5 \
	margin=5 \
	blur_radius=20 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:14.0" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:SemiBold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=2 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"


# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:12.0"
  icon.color="$ICON_COLOR"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.font="$FONT:Semibold:11.0"
  label.color="$LABEL_COLOR"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  padding_right="$PADDINGS"
  padding_left="$PADDINGS"
  background.height=30
  background.corner_radius=9
  background.border_width=0
  popup.background.border_width=1
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)
sketchybar --default "${defaults[@]}"

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/input.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuration loaded.."
