# NOTE: This is only to set up a simple kind cluster with the consistent image
# used.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Ref: https://github.com/kubernetes-sigs/kind/releases
  - role: control-plane
    image: kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
  - role: worker
    image: kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authorization-mode: "AlwaysAllow"
