# WIP - not everything is configured

# Using a bulk of example setup:
# Ref:
# https://github.com/starship/starship/blob/4fa7395c9eabc0745c6eaa1e3dabd3feefeef5e9/docs/.vuepress/public/presets/toml/pastel-powerline.toml

format = """
$os\
[](bg:#181D38 fg:#444444)\
$shell\
[](bg:#0A2239 fg:#181D38)\
$username\
[](bg:#123F68 fg:#0A2239)\
$directory\
[](bg:#18548B fg:#123F68)\
$git_branch\
$git_status\
[](bg:#EBEBEB fg:#18548B)\
[](#EBEBEB)\
$fill\
[](#EBEBEB)\
$cmd_duration\
[](bg:#EBEBEB fg:#18548B)\
$direnv\
[](bg:#18548B fg:#444444)\
$jobs\
$time\
$line_break\
$character
"""

[os]
disabled = false # Disabled by default
style = "bg:#444444"
format = "[ $symbol ]($style)"
[os.symbols]
Macos = ""
NixOS = "󱄅"

[shell]
disabled = false # Disabled by default
style = "bg:#181D38"
format = '[ $indicator ]($style)'
fish_indicator = '󰈺'
bash_indicator = ''

[username]
show_always = true
style_user = "bg:#0A2239"
style_root = "bg:#0A2239"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:#123F68"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"
repo_root_style = "bg:#123F68 bold fg:#9DD1F1"
before_repo_root_style = "bg:#123F68 fg:#031927"
read_only_style = "bg:#123F68 fg:red"
repo_root_format = "[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)"
# TODO: Check out https://github.com/starship/starship/issues/6166 for repo visibility support

# Use fish style notation of a single character for truncated path.
fish_style_pwd_dir_length = 1

# NOTE: The above fish style requires there is no substitutions defined. For
# now, I prefer the fish style (and that's what I use with Powerline10k), I'm
# disabling the below.

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = " "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[git_branch]
symbol = ""
style = "bg:#18548B fg:#222222"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#18548B fg:#222222"
format = '[$all_status$ahead_behind ]($style)'

[fill]
symbol = "─"
style = "fg:#EBEBEB"

[cmd_duration]
format = '[  $duration ]($style)'
style = "bg:#EBEBEB fg:#222222"

[direnv]
disabled = false # Disabled by default
format = '[ 󱄅 $allowed ]($style)'
style = "bg:#18548B fg:#222222"
symbol = '󱄅'
allowed_msg = ' '
not_allowed_msg = ' '
denied_msg = ' '

[time]
disabled = false # Disabled by default
format = '[ $time ]($style)'
time_format = '%T'
style = 'bg:#444444'
