# This file content is mainly generated by `nixos-generate-config` on UTM:
#
#     /etc/nixos/configuration.nix
#     /etc/nixos/hardware-configuration.nix
#
# While most of the configurations are kept as generated, there are some parts
# that have been added, removed, or modified.

{ config
, lib
, pkgs
, modulesPath
, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "uhci_hcd" "virtio_pci" "usbhid" "usb_storage" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # By default, NixOS uses 'by-uuid', but label is more convenient.
  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # NOTE: useDHCP is a part of the generated config, but not using it.
  # networking.useDHCP = lib.mkDefault true;
}
