# This file content was originally generated by `nixos-generate-config` on
# UTM:
#
#     /etc/nixos/configuration.nix
#     /etc/nixos/hardware-configuration.nix
#
# It has since been generalised to boot under either UTM or Parallels
# Desktop on Apple Silicon: the initrd module list is a superset covering
# both hypervisors' disk presentations, and all filesystems are mounted by
# label so the device naming (/dev/vda vs /dev/sda vs /dev/nvme0n1) doesn't
# matter. The labels are created by `machine-setup/mbp-utm/prepare-vm.sh`.
#
# Other configurations for this machine can be found in other files.

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "uhci_hcd"
    # UTM/QEMU presents the disk as virtio-blk (/dev/vda).
    "virtio_pci"
    "virtio_blk"
    "virtio_scsi"
    # Parallels presents the disk via SCSI/SATA (/dev/sda) or NVMe
    # depending on the VM hardware config -- cover all of them.
    "sd_mod"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # By default, NixOS uses 'by-uuid', but label is more convenient.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # `prepare-vm.sh` creates the swap partition with `mkswap -L swap`.
  # `nofail` keeps boot from stalling on VMs where the label is missing
  # (e.g. a swap partition recreated by hand without `-L swap` -- relabel
  # with `swaplabel -L swap /dev/<swap-partition>` to activate it).
  swapDevices = [
    {
      device = "/dev/disk/by-label/swap";
      options = [ "nofail" ];
    }
  ];
}
