window:
  startup_mode: Maximized
  dynamic_title: true
  opacity: 0.85
  padding:
    x: 0
    y: 0

colors:
  # primary:
  #   background: "0x191919"
  #   foreground: "0xeaeaea"

  # Taken from Nord Alacritty
  # Ref: https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml
  primary:
    background: "#2e3440"
    foreground: "#d8dee9"
    dim_foreground: "#a5abb6"
  cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  vi_mode_cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  selection:
    text: CellForeground
    background: "#4c566a"
  search:
    matches:
      foreground: CellBackground
      background: "#88c0d0"
    bar:
      background: "#434c5e"
      foreground: "#d8dee9"
  normal:
    black: "#3b4252"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#88c0d0"
    white: "#e5e9f0"
  bright:
    black: "#4c566a"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#8fbcbb"
    white: "#eceff4"
  dim:
    black: "#373e4d"
    red: "#94545d"
    green: "#809575"
    yellow: "#b29e75"
    blue: "#68809a"
    magenta: "#8c738c"
    cyan: "#6d96a5"
    white: "#aeb3bb"

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: Fira Code
    style: Regular

  # Bold font face
  bold:
    family: Fira Code
    style: Bold

  # Italic font face
  italic:
    family: Fira Code
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Fira Code
    style: Bold Italic

  # Point size
  size: 12.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

mouse:
  hide_when_typing: true
  hints:
    # URL launcher
    #
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    launcher: open

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  # When set to `true`, selected text will be copied to both the primary and
  # the selection clipboard. Otherwise, it will only be copied to the selection
  # clipboard.
  save_to_clipboard: true

shell:
  program: /opt/homebrew/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main

key_bindings:
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: M, mods: Alt, chars: "\x1bm" }
  - { key: Period, mods: Alt, chars: "\x1b." }
  - { key: Back, mods: Command, chars: "\x15" }
  # Tmux related key bindings
  #
  # Ref:
  # https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/
  #
  # Because tmux prefix key is set to Ctrl-q, making F1 as the same as Ctrl-q.
  # Also, all other lines with `\x11` is meant that the prefix of Ctrl-q being
  # invoked first.
  #
  # `xxd -psd` to find the sequence.
  - { key: F1, chars: "\x11" }
  - { key: F2, chars: "\x11\x74" }
  - { key: D, mods: Command, chars: "\x11\x76" }
  - { key: D, mods: Command|Shift, chars: "\x11\x73" }
  - { key: W, mods: Command, chars: "\x11\x78" }
  - { key: H, mods: Command, chars: "\x11\x68" }
  - { key: J, mods: Command, chars: "\x11\x6a" }
  - { key: K, mods: Command, chars: "\x11\x6b" }
  - { key: L, mods: Command, chars: "\x11\x6c" }
  - { key: T, mods: Command, chars: "\x11\x63" }
  # Window selection
  - { key: Key1, mods: Command, chars: "\x11\x31" }
  - { key: Key2, mods: Command, chars: "\x11\x32" }
  - { key: Key3, mods: Command, chars: "\x11\x33" }
  - { key: Key4, mods: Command, chars: "\x11\x34" }
  - { key: Key5, mods: Command, chars: "\x11\x35" }
  - { key: Key6, mods: Command, chars: "\x11\x36" }
  - { key: Key7, mods: Command, chars: "\x11\x37" }
  - { key: Key8, mods: Command, chars: "\x11\x38" }
  - { key: Key9, mods: Command, chars: "\x11\x39" }
  - { key: Left, mods: Command|Alt, chars: "\x11\x70" }
  - { key: Right, mods: Command|Alt, chars: "\x11\x6e" }
  # Window resize
  - { key: Left, mods: Command, chars: "\x11\x48" }
  - { key: Down, mods: Command, chars: "\x11\x4a" }
  - { key: Up, mods: Command, chars: "\x11\x4b" }
  - { key: Right, mods: Command, chars: "\x11\x4c" }
  - { key: Tab, mods: Control, chars: "\x11\x06" }
  # Move panes with prefix + arrows.
  - { key: Left, mods: Alt, chars: "\x11\x1b\x5b\x44" }
  - { key: Down, mods: Alt, chars: "\x11\x1b\x5b\x42" }
  - { key: Up, mods: Alt, chars: "\x11\x1b\x5b\x41" }
  - { key: Right, mods: Alt, chars: "\x11\x1b\x5b\x43" }
  # Other shortcuts which need tweaking for Dvorak
  - { key: S, mods: Control, chars: "\x13" } # Make qre to send the same sequence
  - { key: V, mods: Control, chars: "\x16" } # Make sure to send the same sequence
  - { key: W, mods: Control, chars: "\x17" } # Make sure to send the same sequence
  - { key: Z, mods: Control, chars: "\x1a" } # Make sure to send the same sequence
