#+title: Windows Machine

I don't use Windows too much, but some devices can be configured so that I can keep Windows for dual boot.

Because Windows takes up a lot of disk space, I need to manage it first before installing NixOS to maximise the disk allocation to NixOS. The steps here are extremely convoluted, but without these steps, I need to keep 250GB for Windows, which is excessively large.

* Remove large files
Remove unused files and large file setup.
#+begin_src cmd
  :: Disable hibernation (frees ~RAM size, e.g. 16-32GB)
  powercfg /hibernate off

  :: Clean up Windows Update cache and old components
  dism /Online /Cleanup-Image /StartComponentCleanup /ResetBase

  :: Remove all restore points
  vssadmin delete shadows /for=C: /all /quiet

  :: Clear Windows temp folders
  del /q /s %TEMP%\*
  del /q /s C:\Windows\Temp\*

  :: Clear Delivery Optimization cache
  del /q /s C:\Windows\SoftwareDistribution\Download\*
#+end_src

** pagefile.sys
Windows takes up the same size of disk space as RAM size with file called ~pagefile.sys~, and this can be a significant chunk (e.g. on Flow Z13, this is 128GB). The below is the Powershell command to remove this and cut it down to minimal size (which is probably not needed in most cases, but keeping it around just in case).
#+begin_src powershell
  Set-CimInstance -Query "Select * from Win32_PageFileSetting where Name='C:\\pagefile.sys'" -Property @{InitialSize = 8192; MaximumSize = 8192}
#+end_src

** System restore cleanup
I should also use ~sysdm.cpl~ GUI to disable System Restore:
- Run: sysdm.cpl
- Go to System Protection tab.
- Select C: and click Configure.
- Select "Disable system protection".
- Click Delete (to clear existing restore points).

Also, for the next step, it's wise to remove the pagefile.sys entirely for now. Within the same ~sysdm.cpl~ session:
- Go to Advanced tab
- Select Performance > "Settings..."
- Go to Advanced tab
- Select Virtual memory > "Change..."
- Delete, and hit Set

I need to restart the machine at this point.

** Defrag
After the restart, I can run the defrag to allow shrinking disk space.
#+begin_src bash
  defrag C: /O /U /V
#+end_src

* Working around BitLocker
Because Windows 11 has BitLocker enabled by default, I need to play with disk encryption to manage the disk space more.

From Powershell:
#+begin_src powershell
  Get-BitLockerVolume
  Disable-BitLocker -MountPoint "C:"
#+end_src

Run ~Get-BitLockerVolume~ multiple times until "Encryption Percentage" shows 0.

Once BitLocker is off, I can use NixOS Installer image to shrink the Windows partition size. (I need to disable Secure Boot from BIOS for USB boot.)
Starting with 145GB to be safe.
#+begin_src bash
  sudo ntfsresize --info --no-action /dev/nvme0n1p3
  sudo ntfsresize --size 145G /dev/nvme0n1p3
#+end_src

And for the partition resize:
#+begin_src bash
  sudo fdisk /dev/nvme0n1
#+end_src

#+begin_example
1. Print current table (Important):
    Type p and hit Enter.
    Write down the "Start" sector of /dev/nvme0n1p3. You MUST use this exact number later.
2. Delete the partition:
    Type d.
    Select partition number 3 (or whatever your Windows partition is).
    Don't panic. The data is still there, just the map is gone.
3. Create new partition:
    Type n.
    Partition number: 3.
    First sector: Type the EXACT START SECTOR you wrote down in step 2. (Default is usually correct, but verify!)
    Last sector: Type +150G.
        Note: This creates a 150 GiB partition.
4. Handle the signature warning:
    If fdisk asks: "Partition #3 contains a NTFS signature. Do you want to remove it?"
    Answer: NO. (Type N). Do not wipe the signature.
5. Verify:
    Type p. Ensure the Start sector is identical to before, and the Size is 150G.
6. Write changes:
    Type w.
#+end_example

Finally, make sure that the partition takes up 150GB:
#+begin_src bash
  # Running this without the --size flag automatically expands to fill the partition
  sudo ntfsresize /dev/nvme0n1p3
#+end_src

After this, reboot back into Windows machine. It fails to load up. I can then choose Advanced Option to get the cmd session up.
With cmd, I can follow something like below.
#+begin_src cmd
  diskpart
  select disk 0
  list partition

  # Likely partition 3
  select partition 3
  detail partition

  # Set this EXACT ID
  set id="ebd0a0a2-b9e5-4433-87c0-68b6b72699c7"

  list volume
  select volume X  # Replace X with the number of your 150GB volume
  assign letter=W  # Give it a temporary letter like W
  exit
#+end_src

And then, check and fix the disk state.
#+begin_src bash
  chkdsk W: /f
#+end_src

Exit and restart. At this point, I get another error booting up, go through advanced options to get to cmd again.
Run the following commands:
#+begin_src bash
  # Check the volume name, which should be set to C
  diskpart
  list volume
  exit

  # Make sure chkdsk doesn't report any error
  chkdsk C: /f /x
  # Rebuild the Boot Files
  bcdboot C:\Windows
  # Break the "Automatic Repair" Loop
  bcdedit /set {default} recoveryenabled No
  bcdedit /set {default} bootstatuspolicy ignoreallfailures
#+end_src

Restart again, and find two OS selections at launch. Choose the one that says "On volume 3".
Windows should start up cleanly, and now I can do the final clean up.
#+begin_src bash
  # Set up BitLcoker back -- this needs restart to do hardware check.
  manage-bde -on C: -UsedSpaceOnly
#+end_src

I should also use ~sysdm.cpl~ GUI to enable System Restore, and pagefile back in place.
- System Protection
  - Go to System Protection tab.
  - Select C: and click Configure.
  - Select "Turn on system protection".
  - Select Max Usage size (around 5GB) and hit OK
- Pagefile
  - Go to Advanced tab
  - Select Performance > "Settings..."
  - Go to Advanced tab
  - Select Virtual memory > "Change..."
  - Custom size of 8192, and hit Set

And some more clean-up, this one is for Windows Recovery.
#+begin_src bash
  reagentc /info
  # If disable, enable
  reagentc /enable
#+end_src

Once this is done, restart, set the Secure Boot back, and start back into Windows to ensure it is working as expected.
After that, I would probably need to clean up temporary disk space Windows used with diagnostic mode. Before proceeding, make sure that the partitions are not actually used by ~Win + X~ -> Disk Management.
#+begin_src bash
  diskpart
  select disk 0

  list partition

  select partition 4
  delete partition override

  select partition 5
  delete partition override

  exit
#+end_src
