[user]
name = "Ryota"

[signing]
behavior = "own"
backend = "gpg"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
pager = ":builtin"
paginate = "auto"
default-command = "log"

[ui.streampager]
wrapping = "word"      # wrap on word boundaries
