# Default setup
icons = true
human = true
layout = "inverted"
suppress-size = true

# Compute file sizes like `du`
# e.g. `erd --config du`
[du]
disk_usage = "block"
icons = true
layout = "flat"
no-ignore = true
no-git = true
hidden = true
level = 1

# Do as `ls -l`
# e.g. `erd --config ls`
[ls]
icons = true
human = true
layout = "inverted"
level = 1
suppress-size = true
long = true

# How many lines of Rust are in this code base?
# e.g. `erd --config rs`
[rs]
icons = true
human = true
layout = "inverted"
disk-usage = "line"
# level = 1
pattern = "\\.rs$"