#+title: Nix with MacBook Pro

This details how I configure my MBP with Nix.

* Quick Setup
Firstly, install Nix.

#+begin_src sh
  sh <(curl -L https://nixos.org/nix/install)
#+end_src

#+begin_quote
  Ref: https://nixos.org/download.html#nix-install-macos
#+end_quote

Then, install ~nix-darwin~:

#+begin_src sh
  nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
  ./result/bin/darwin-installer
#+end_src

#+begin_quote
  Ref: https://github.com/LnL7/nix-darwin/
#+end_quote

In order to get Homebrew based appliactions installed, I also need to install Homebrew out of Nix setup.

#+begin_src sh
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src

** Build with Config
Once all of the above is in place, I can get my config from this repo, and run a rebuild.
For the initial setup, I don't need to get the repository via ~git~, and simply use a ~curl~ instead.

#+begin_src sh
  darwin-rebuild switch --flake ~/Coding/github.com/rytswd/nix-config#ryota-mbp
#+end_src


* Non-Nix Setup
While a lot can be achieved with Nix, there are still a few items that are not managed by Nix on macOS. It may be because I have not figured out how to handle them using Nix, but here are the list of items I need to update.

- Adjust keyboard preferences (I use Dvorak + QWERTY Cmd mainly, but configure a few more keyboards as well)
- Remove spotlight shortcut
- Add shortcut for language selection with Cmd + Space
- Open up all the apps installed via Homebrew (esp. Raycast and Arc)
- Update the default browser
- Download Ghostty and move to ~/Applications~ directory
- Add finger IDs
- Configure Raycast shortcuts
- Update Dropbox and other cloud storage save location
- Set calendar start date to Sunday
- Show volume icon in the menu bar
- Hide the menu bar by default
- Disable auto rearrange spaces
- Switch to space when selecting app
- Show battery percentage

There are some that I know I can manage using the Nix configurations here, but not managed yet:

- Install KeyCastr
