# This file content is mainly generated by `nixos-generate-config` with NixOS
# installer:
#
#     /etc/nixos/configuration.nix
#     /etc/nixos/hardware-configuration.nix
#
# While most of the configurations are kept as generated, there are some parts
# that have been added, removed, or modified.
#
# Other configurations for this machine can be found in other files.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
      kernelModules = [];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Be careful updating this.
  # NOTE: Sticking to this version which is compatible with ZFS.
  boot.kernelPackages = pkgs.linuxPackages_6_17;
}
