#+title: Initial Setup Steps

* NixOS installer image
I set up this machine with a dedicated installer ISO, which you can find in this repo. The installer is essentially the same as official minimal ISO, but some extra tools configured such as pcscd for YubiKey handling. You can find more in ~/nixos-config/iso/README.org~.

* Windows setup
If I were to keep Windows on the machine, I need to resize the Windows disk space so that I can use the rest of the disk space for other usages.

The steps here are extremely convoluted, but without these steps, I need to keep 250GB for Windows, which is excessively large.
I have all the details in ~/machine-setup/windows-machine/README.org~.

* On device operation
Once the NixOS installer is started up, I need some action on device. After this is done, I can manage the rest using SSH.

** Network setup
In order to get the network working, I need to launch ~nmtui~.

** Credential options
The credential options -- SSH agent forwarding from a helper machine, pulling the SSH stub keys from YubiKey with ~ssh-keygen -K~, or proceeding degraded with neither -- are covered by [[file:../../docs/runbooks/credential-bootstrap.org]].


* Main configuration from NixOS Installer
The generic flow -- remote access and credentials, repo clone to ~/tmp/~, disko, ~nixos-install~, and the post-install tail including the host key handover for SOPS Nix -- is covered by [[file:../../docs/runbooks/bare-metal-install.org]], with a guided script for the whole sequence:
#+begin_src bash
  nix run github:rytswd/nix-config#install -- asus-rog-flow-z13-2025
#+end_src

The sections below are only the deltas for this machine.

** Windows dual boot
If I were to drop Windows dual boot, disko can wipe and reconfigure the disk fully declaratively. As of writing in Feb 2026, I'm opting to keep Windows partition. Because of this, there are a few manual actions needed.

*** Secure Boot
In order to allow clean boot for both NixOS and Windows, I need to keep Secure Boot with BitLocker for Windows, and let it work with NixOS the same way. I'm using Limine to handle this.

*** Windows partition
I can shrink the Windows C drive after doing extensive Windows disk space clean-up steps, detailed above.

In order to allow disko to manage without breaking Windows partittion, I need some manual partitioning.
#+begin_src console
  $ sudo fdisk -l
  Disk /dev/nvme0n1: 953.87 GiB, 1024209543168 bytes, 2000409264 sectors
  Disk model: MTFDKBK1T0QGN-1BN1AABGA
  Units: sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 4096 bytes / 4096 bytes
  Disklabel type: gpt
  Disk identifier: EF2B6D05-E94E-40F4-8E91-2FE86951CE8B

  Device              Start        End   Sectors  Size Type
  /dev/nvme0n1p1       2048     923647    921600  450M EFI System
  /dev/nvme0n1p2     923648     956415     32768   16M Microsoft reserved
  /dev/nvme0n1p3     956416  315529215 314572800  150G Microsoft basic data
  /dev/nvme0n1p4 1938903040 1941155839   2252800  1.1G Windows recovery environment
  /dev/nvme0n1p5 1941155840 1999876095  58720256   28G Microsoft basic data
  /dev/nvme0n1p6 1999876096 2000408575    532480  260M Windows recovery environment
#+end_src

With this partition in place, I can create a new partition
#+begin_src bash
  # 1. Create 1GB ESP first (right after partition 3)
  sudo sgdisk -n 7:315529216:+1G -t 7:EF00 -c 7:nixos-esp /dev/nvme0n1

  # 2. Create NixOS root partition (remaining ~773GB, ending just before partition 4)
  sudo sgdisk -n 8:0:1938903039 -t 8:8300 -c 8:nixos /dev/nvme0n1
#+end_src

When using dual boot, I need to use ~disko-dual-boot.nix~, and be sure not to destroy the existing partitions.

** Partitioning with disko
Partition setup can be done using disko https://github.com/nix-community/disko.

The command used is slightly different depending on whether I need Windows dual boot or not.

*** With dual boot
With the repository cloned in ~/tmp/~ directory, I can run the following command (this also assumes the use of custom ISO in this repository)
#+begin_src bash
  sudo nix run github:nix-community/disko/latest -- --mode format,mount /tmp/nix-config/nixos-config/asus-rog-flow-z13-2025/disko-dual-boot.nix
#+end_src

NOTE: If this is based on stock NixOS without ~nix-command~ and ~flakes~ flags, add them like below:
#+begin_src bash
  sudo nix --experimental-features "nix-command flakes"  run github:nix-community/disko/latest -- --mode format,mount /tmp/nix-config/nixos-config/asus-rog-flow-z13-2025/disko-dual-boot.nix
#+end_src

After a short while, this asks whether I would like to continue with the reformatting step, and when I confirm with "yes", I would also get prompted for a password phrase for LUKS.

Shortly after, the formatting completes, and I can check the mount setup:
#+begin_src bash
  mount | grep /mnt
  lsblk
#+end_src

Once disk partition is complete, move onto the rest of the Nix configuration.

*** (Reference Only) NixOS only
Note that, as of writing in Feb 2026, my configuration assumes the dual boot setup, and thus this NixOS only disko setup is not used.

With the repository cloned in ~/tmp/~ directory, I can run the following command (this also assumes the use of custom ISO in this repository)
#+begin_src bash
  sudo nix run github:nix-community/disko/latest -- --mode destroy,format,mount /tmp/nix-config/nixos-config/asus-rog-flow-z13-2025/disko-nixos-only.nix
#+end_src

NOTE: If this is based on stock NixOS without ~nix-command~ and ~flakes~ flags, add them like below:
#+begin_src bash
  sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko/latest -- --mode destroy,format,mount /tmp/disko-config.nix
#+end_src

*** Info: Open LUKS manually
When I need to restart the installer, I will need to reopen LUKS manually.
#+begin_src bash
  # Open LUKS (will prompt for your passphrase)
  cryptsetup open /dev/disk/by-partlabel/nixos crypted
#+end_src

I can confirm the status by running ~lsblk~.

And simply run disko to mount everything 
#+begin_src bash
  sudo nix run github:nix-community/disko/latest -- --mode mount /tmp/nix-config/nixos-config/asus-rog-flow-z13-2025/disko-dual-boot.nix
#+end_src

If I had to run this /after/ getting the NixOS system up and running, I may get an error saying zpool won't import as it was used by other system. I can run the following command:
#+begin_src bash
  zpool import -f -R /mnt zroot
#+end_src

And then run the disko to mount again.


*** Info: Close LUKS for rerun
When the disko needs to be run again due to unexpected restarts etc., I would have to run the following commands to close LUKS block.
#+begin_src bash
  # Unmount everything
  umount -R /mnt

  # Export ZFS pool
  zpool export zroot

  # Close LUKS
  cryptsetup close crypted

  # Wipe LUKS header so disko can reformat cleanly
  wipefs -a /dev/disk/by-partlabel/nixos
#+end_src

** Boot entry for Limine
After the generic ~nixos-install~ phase from the runbook, I need to make sure that the boot entry is added -- Limine can handle Windows with chainloading.
#+begin_src bash
  sudo nixos-enter --root /mnt -c "NIXOS_INSTALL_BOOTLOADER=1 /nix/var/nix/profiles/system/bin/switch-to-configuration boot"
  sudo efibootmgr --create --disk /dev/nvme0n1 --part 7 --label "Limine" --loader '\EFI\BOOT\BOOTX64.EFI'
#+end_src

The remaining pre-reboot steps -- the chroot ~nixos-rebuild boot~ and the host key handover for SOPS Nix -- are the generic post-install tail in [[file:../../docs/runbooks/bare-metal-install.org]].


* Final configuration from NixOS
At this point, the system should be fully up and running. This step is necessary mainly for dual boot.

** Secure Boot setup
The following commands need to be run:
#+begin_src bash
  sudo sbctl create-keys

  # Check
  sudo sbctl list-enrolled-keys
  sudo sbctl status
  sudo sbctl verify

  # Sign the Limine bootloader
  sudo sbctl sign -s /boot/efi/boot/BOOTX64.EFI
  # Do NOT sign the kernel, Limine is all I need the Secure Boot for.

  # Confirm the EFI images are signed
  sudo sbctl verify
#+end_src

At this point, I need to restart the machine and need to go into BIOS.
#+begin_src bash
  sudo systemctl reboot --firmware-setup
#+end_src

With the new key created with ~sbctl create-keys~, I need to make sure BIOS firmware stores this information -- but in order to do this, I need to first remove the existing keys. This is the sequence of actions I need to take
#+begin_example
  Tab: Security -> Secure Boot

  Secure Boot Control -> change this to "Enabled"
  # At this point I should see "Expert Key Management"

  Expert Key Management -> Reset to Setup Mode

  # Once again, keep Secure Boot disabled for launching NixOS
  Secure Boot Control -> change this to "Disabled"
#+end_example

At this point, Limine may complain saying Blake2b hash for Linux image does not match. This is expected due to the fact I signed the boot image earlier, and will need to rebuild to correct the hash entry.
Once I get back into NixOS machine, I can run the following to complete the setup.
#+begin_src bash
  sudo sbctl enroll-keys --microsoft
#+end_src

After this step, I should do a ~nixos-rebuild~ to ensure the image is hashed correctly, and then get back to BIOS to enable Secure Boot.
#+begin_src bash
  sudo systemctl reboot --firmware-setup
#+end_src

#+begin_example
  Tab: Security -> Secure Boot

  Secure Boot Control -> change this to "Enabled"
#+end_example

** Adjust Nix input
After the Secure Boot setup is fully in place, I can comment-in the Secure Boot flag on Limine in my ~configuration.nix~.


